name: Clean Old Logs

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0'  # Setiap Minggu

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Setup GitHub CLI
        run: sudo apt-get install gh

      - name: Delete Workflow Runs
        run: |
          gh run list --limit 100 | grep "completed" | awk '{print $1}' | xargs -I {} gh run delete {} -y
