name: Fetch Proxies

on:
  schedule:
    - cron: ''  # Menjalankan setiap 6 jam
  workflow_dispatch:  # Bisa dijalankan secara manual

jobs:
  fetch-proxies:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests

      - name: Run fetch script
        run: python fetch_proxies.py  # Sesuaikan dengan nama file skrip

      - name: Upload proxies.txt as artifact
        uses: actions/upload-artifact@v4
        with:
          name: proxies
          path: proxies.txt

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions@github.com"
          git add proxies.txt
          git commit -m "Update proxies.txt [CI Skip]" || echo "No changes to commit"
          git push
